### ISSUE TITLE
Firefox Support?

### ISSUE THREAD

**Issue by mfkp** [opentok/opentok-hardware-setup.js#14]
I was using this widget for a while, until I realized it doesn't work on Firefox.

What's the reason that it's chrome only? Any way to make a simplified version of it for Firefox?

**Comment by thepatrick** [comment]
The reason for being Chrome only is that the APIs it uses in the current release of OpenTok.js [OT.getDevices](https://tokbox.com/developer/sdks/js/reference/OT.html) are not supported in Firefox (the underlying feature, device enumeration, was not available in Firefox at the last release).

The next release of OpenTok.js should support Firefox, but may require Firefox Beta to use it.

(You can see if it would work by trying `navigator.mediaDevices.enumerateDevices().then(function(devices){ console.log('devices', devices); }).catch(function(err){ console.log('error', err); });` in the developer tools console in Firefox. If you get anything other than a "Promise { state: Pending }" and then a like similar to "devices Array [MediaDeviceInfo, MediaDeviceInfo, ...]" it won't work)

**Comment by thepatrick** [comment]
OpenTok.js v2.6.1 (released today) supports getDevices in versions of Firefox that support the necessary API, which I believe was added in Firefox v39.
