### ISSUE TITLE
Broken in chrome 43.0.2357.134

### ISSUE THREAD

**Issue by mfkp** [opentok/opentok-hardware-setup.js#16]
Just updated my browser, and this library is broken in chrome now.

`Error: There are no audio or video devices available`

This was previously working in the last version of Chrome that I was running.

**Comment by thepatrick** [comment]
@mfkp this was caused by a bug in the latest version of opentok.js - a fix for that is being tested now and should be released soon. (I'm not 100% sure of the exact time frame, sorry).

As an interim fix you can use code similar to https://github.com/opentok/opentok-hardware-setup.js/pull/15/files

**Comment by mfkp** [comment]
thanks @thepatrick, but i've already worked out my own solution to using this library, it's just not stable enough for my production system. you've been responsive and helpful, but hopefully tokbox will get these types of issues sorted before competitors (ahem twilio video) do it for you.

**Comment by mfkp** [comment]
FYI I also posted about this in the tokbox forums as well, guess I'll have to disable the auto-updating and host my own local version of opentok.js to prevent this in the future.

https://forums.tokbox.com/opentok-plugin/ie-plugin-prompt-for-safari-t45914#p60384

**Comment by thepatrick** [comment]
OpenTok.js v2.6.1 has been deployed to https://static.opentok.com/v2/js/opentok.min.js that resolves this issue. 

@mfkp please be aware that if you do host your own copy of opentok.js you should talk to our support team first - it may not be a supported configuration.
