### ISSUE TITLE
firefox browser

### ISSUE THREAD

**Issue by burhanturkce** [opentok/opentok-hardware-setup.js#17]
there are several problems in latest firefox browser. Mic. is ok but it is not able to acquire video...  Can you check it with firefox ?

**Comment by aullman** [comment]
Yes, I noticed that in Firefox 39 (current production version) the Camera just keeps spinning. Unless you have a second camera and you switch to that then the camera shows up.

In Nightly it doesn't even get past the first prompt. You just get a black screen with spinning video.

I have filed an issue internally and we'll try to get this fixed.

**Comment by michaeljolley** [comment]
Closing as stale. Please open a new issue if the problem or question persists.
