### ISSUE TITLE
Is possible to get audio output ?

### ISSUE THREAD

**Issue by bgobi1991** [opentok/opentok-hardware-setup.js#18]
Hi ,

how to get audio out like speaker ?

**Comment by aullman** [comment]
This component does not play out any audio because if it did you would get a horrible looping echo effect because the sound from your speaker will go directly back into your microphone.

**Comment by bgobi1991** [comment]
Hi,

I would like to get some clarification with get devices method i.e.
OT.getDevices(callback), This method is currently returning only the audio
input and video input. But we are in need of one more additional
information (ie audio output) which is not currently returning by that
method. Is there any other way to get that data through any of the other
methods rendered by opentok? If it is not readily available, please let us
know the possible way to get it.


On Thu, Aug 6, 2015 at 5:51 PM, Adam Ullman <notifications@github.com>
wrote:

> Closed #18
> <https://github.com/opentok/opentok-hardware-setup.js/issues/18>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentok/opentok-hardware-setup.js/issues/18#event-375232839>
> .
>



-- 
Regards
Gobi Baskaran

**Comment by aullman** [comment]
Oh, sorry, I misunderstood. Audio output devices aren't available to us in the browsers yet and so we can't provide them. They are currently available in Chrome 45 (beta) behind a flag. When they do become available and not behind a flag we will be able to expose them. More information can be found at:

https://code.google.com/p/webrtc/issues/detail?id=2243
https://webrtc.github.io/samples/src/content/devices/multi/

**Comment by joelmaranhao** [comment]
Aren't audio output devices are now available, but still can't get it through `OT.getDevices()`. is this still in the pipeline?
