### ISSUE TITLE
How to get device name ?

### ISSUE THREAD

**Issue by bgobi1991** [opentok/opentok-hardware-setup.js#20]
Hi,

How to get microphone device name and video device name ?

**Comment by aullman** [comment]
Is the name not showing up for you in the hardware setup component? Or you want to know how to just get the name for your own code?

**Comment by bgobi1991** [comment]
yes, The name not showing up for my hardware setup component

**Comment by aullman** [comment]
What browser/platform are you on? It's working fine for me in Chrome/OSX.

![image](https://cloud.githubusercontent.com/assets/733672/9433720/c7a263be-4a79-11e5-8dbe-539cd4b9bcba.png)

**Comment by bgobi1991** [comment]
internet explorer 10 or above(with opentok plugin)

**Comment by michaeljolley** [comment]
Closing as stale. Please open a new issue if the problem or question persists.
