### ISSUE TITLE
Exception when copying styles on Chrome

### ISSUE THREAD

**Issue by csand** [opentok/opentok-hardware-setup.js#23]
Issue on Chrome 44 when copying the container's styles to the target element. Message is:

`Uncaught TypeError: Cannot set property length of #<CSSStyleDeclaration> which has only a getter`

Exception is thrown [here](https://github.com/opentok/opentok-hardware-setup.js/blob/master/js/opentok-hardware-setup.js#L392).

**Comment by csand** [comment]
This occurs when `insertMode` is set to `replace`.

**Comment by michaeljolley** [comment]
Closing as stale. Please open a new issue if the problem or question persists.
